name : GitHub action demo pipeline 

on:
  push:
    branches:
     - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
  steps:
    -name : Checkout code
    uses : action/checkout@v2

    -name: print message
    -run : echo "welcome shona baby" 


